### PR TITLE
Set instance variable values at initialization and remove unused variables to avoid spamming rake warnings.

### LINKED ISSUE #2: Rake 11.0+ requires all instance variables to be initialized
Sample Warnings:

```
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/lex.rb:156: warning: assigned but unused variable - matched                                                                                                                               [658/996]
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/production.rb:30: warning: method redefined; discarding old line
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/production.rb:34: warning: method redefined; discarding old lr0_added
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/production.rb:38: warning: method redefined; discarding old reduced
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:6: warning: `-' after local variable or literal is interpreted as binary operator
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:6: warning: even though it seems like unary operator
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:84: warning: assigned but unused variable - sprec
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:152: warning: assigned but unused variable - sprec
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:371: warning: assigned but unused variable - dr_set
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:2: warning: /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:2: warning: loading in progress, circular require considered harmful - /
usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/ply_dump.rb
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:5:in  `<main>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:5:in  `select'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:17:in  `block in <main>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:17:in  `require'
        from /usr/local/google/home/username/repo/fluent-plugin-google-cloud/test/plugin/base_test.rb:16:in  `<top (required)>'
        from /usr/local/google/home/username/repo/fluent-plugin-google-cloud/test/plugin/base_test.rb:16:in  `require'
        from /usr/local/google/home/username/repo/fluent-plugin-google-cloud/test/helper.rb:40:in  `<top (required)>'
        from /usr/local/google/home/username/repo/fluent-plugin-google-cloud/test/helper.rb:40:in  `require'
        from /usr/local/google/home/username/repo/fluent-plugin-google-cloud/lib/fluent/plugin/out_google_cloud.rb:24:in  `<top (required)>'
        from /usr/local/google/home/username/repo/fluent-plugin-google-cloud/lib/fluent/plugin/out_google_cloud.rb:24:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2.rb:16:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2.rb:16:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2/config_service_v2_client.rb:26:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-cloud-logging-1.6.6/lib/google/cloud/logging/v2/config_service_v2_client.rb:26:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-gax-1.7.0/lib/google/gax.rb:33:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-gax-1.7.0/lib/google/gax.rb:33:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-gax-1.7.0/lib/google/gax/path_template.rb:30:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/google-gax-1.7.0/lib/google/gax/path_template.rb:30:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly.rb:4:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly.rb:4:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:5:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:5:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/ply_dump.rb:1:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/ply_dump.rb:1:in  `require'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:2:in  `<top (required)>'
        from /usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/lr_table.rb:2:in  `require'

/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:289: warning: method redefined; discarding old grammar
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:338: warning: method redefined; discarding old rules
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:349: warning: method redefined; discarding old prec_rules
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:290: warning: instance variable @grammar not initialized
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:362: warning: instance variable @parsed_rules not initialized
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/rule_parser.rb:8: warning: instance variable @lexer_class not initialized
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/parse/rule_parser.rb:25: warning: instance variable @grammar not initialized
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/lex.rb:196: warning: instance variable @token_regexps not initialized
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/lex.rb:196: warning: instance variable @token_regexps not initialized
/usr/local/google/home/username/.rvm/gems/ruby-2.6.3/gems/rly-0.2.3/lib/rly/yacc.rb:290: warning: instance variable @grammar not initialized
```

### PR DESCRIPTION
**Pull request by qingling128**
Fixes https://github.com/farcaller/rly/issues/2.

### CODE REVIEW

**Comment by farcaller** [comment]
Do the tests work for you locally?

**Comment by qingling128** [comment]
I saw the same errors locally as well. I saw this sentence `Failures listed here are expected and do not affect your suite's status`. So I thought it's fine. On a second look, the following one seems to be a real failure:

```
Failures:

  1) Rly::LRTable attaches the lookahead symbols to grammar rules FIXED
     Expected pending 'verify that values in LRItem#lookaheads are meaningful' to fail. No error was raised.
     # ./spec/parse/lr_table_spec.rb:195
```

Looking.

**Comment by qingling128** [comment]
I just tried backing off my changes line by line to isolate the issue. It turned out that the failure happened on the master branch before this commit as well:
https://travis-ci.org/farcaller/rly/builds/81275591.

Any chance you still remember what that error is about (I know it's been a few years...)?

**Comment by farcaller** [comment]
Looking at it the tests are broken because of some files missing and I have no clue where my local checkout is – that was three notebooks ago.

**Comment by farcaller** [comment]
Thanks for fixing this!

**Pull request merged**
